<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes"/>
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
    
    <!-- Settlements fixes -->
    <xsl:template match="Settlement[@id='village_V7_2']/@posX"><xsl:attribute name='posX'>164.953</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V7_2']/@posY"><xsl:attribute name='posY'>338.910</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A5_3']/@posX"><xsl:attribute name='posX'>550.766</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A5_3']/@posY"><xsl:attribute name='posY'>135.541</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A7_4']/@posX"><xsl:attribute name='posX'>382.790</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A7_4']/@posY"><xsl:attribute name='posY'>95.161</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW6_4']/Components/Village/@bound"> <xsl:attribute name='bound'>Settlement.town_EW6</xsl:attribute> </xsl:template>

    <!-- Cereann -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_B1']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B1_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B1_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B1_3']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B1_4']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B3']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B3']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B3_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B3_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B3_3']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B7_3']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B4']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B4']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B4_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B4_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B4_3']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B4_4']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B2']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B2_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B2_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B2_3']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B5']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B5']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B5_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B5_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B5_3']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_B5']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B5']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B5_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B5_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B3']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B3']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B3_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B3_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B8']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B8']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B8_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B8_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B7']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B7']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B7_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B7_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B2']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B2_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B2_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B4']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B4']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B4_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B4_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW5']/@owner"><xsl:attribute name='owner'>Faction.clan_battania_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW5']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW5_1']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW5_2']/@culture"><xsl:attribute name='culture'>Culture.battania</xsl:attribute></xsl:template>

    <!-- Iustrium -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_ES2']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES1_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES2_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES2_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES2_4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES8']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES8']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES8_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES8_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES8_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A4']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A4_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A4_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A4_4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES1']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES1_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES1_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES1_4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A2']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A2_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A2_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A2_4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A13']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A13']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A13_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A13_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A13_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_ES4']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES4_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES4_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES5']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES5']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES5_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES5_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A8']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A8']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A8_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A8_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES1']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES1_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES1_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A6']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A6']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A6_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A6_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A12']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A12']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A12_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A12_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>

    <!-- Kratorios -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_ES3']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES3_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES3_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES3_3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES6']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES6']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES6_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES6_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES8_3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW3']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW3_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW3_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW3_3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW6']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW6']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW6_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='rhoanne_EW6_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW6_3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW6_4']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW5']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW5']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW5_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW5_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW2_3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES4']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES4']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES4_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES4_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES4_3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW2']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW2_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW2_3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW2_4']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_EW3']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW3']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW3_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW3_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES8']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES8']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES8_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES8_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW7']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW7']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW7_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW7_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN6']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN6']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN6_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN6_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW2']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW2_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW2_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES6']/@owner"><xsl:attribute name='owner'>Faction.clan_empire_south_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES6']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES6_1']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES6_2']/@culture"><xsl:attribute name='culture'>Culture.empire</xsl:attribute></xsl:template>

    <!-- Lysellois -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_V6']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V6']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_4']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V3']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V3_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V3_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V3_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V3_4']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V7']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V7']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V7_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V7_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V7_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V5']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V5']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V5_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V5_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V5_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V1']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V1_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V1_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V11']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V11']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_5']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_6']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V11_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_V3']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V3_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V3_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V6']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V6']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V6_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V6_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V1']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V1_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V1_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V2']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V2_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V2_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B1']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B1_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B1_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V7']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V7']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V7_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V7_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>

    <!-- Qinguo -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_K2']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_K2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K2_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K2_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K2_3']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K2_5']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_K7']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_K7']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K7_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K7_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K7_3']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES7']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES7']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES7_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES7_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES7_3']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES5']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES5']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES5_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES5_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES5_3']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_K6']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_K6']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K6_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K6_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K6_3']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_K8']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_K8']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K8_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K8_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_K8_3']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_K2']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K2_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K2_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K3']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K3']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K3_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K3_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K7']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K7']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K7_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K7_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES3']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES3']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES3_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES3_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES2']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES2_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES2_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K8']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K8']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K8_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K8_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K10']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K10']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K10_1']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K10_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K11']/@owner"><xsl:attribute name='owner'>Faction.clan_qinguo_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_K11']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K2_4']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_K11_2']/@culture"><xsl:attribute name='culture'>Culture.qinguo</xsl:attribute></xsl:template>

    <!-- Rekgeist -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_EN1']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN1_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN1_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN1_3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S1']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S1_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S1_3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN3']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN3_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN3_3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN3_4']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S3']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S3_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S3_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN2']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN2_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN2_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S8']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S8']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S8_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S8_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_EW8']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW8']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW8_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW8_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN9']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN9']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN9_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN9_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S10']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S10']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S10_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN1']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN1_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN1_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S5']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S5']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S5_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S5_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN3']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN3_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN3_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S4']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S4']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S4_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S4_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S2']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S2_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S2_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>

    <!-- Scarhok -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_V8']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V8']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V8_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V8_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V8_3']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V2']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V2_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V2_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V2_3']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V9']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V9']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V9_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V9_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B6']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_B6']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_B4_5']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V6_3']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V6_4']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S7']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S7']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S7_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S7_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S7_3']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V4']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V4']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V5_3']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V4_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_V5']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V5']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V5_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V5_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V8']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V8']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V8_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V8_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V4']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V4']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V4_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S3']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S3']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S3_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S3_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S1']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S1_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S1_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B6']/@owner"><xsl:attribute name='owner'>Faction.clan_vlandia_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B6']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B6_1']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B6_2']/@culture"><xsl:attribute name='culture'>Culture.vlandia</xsl:attribute></xsl:template>

    <!-- Zulizwe -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_EW4']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW4']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW4_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW1_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW4_3']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW4_4']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A6']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A6']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A6_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A6_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A6_3']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A6_4']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A9']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A9']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A9_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A9_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A9_3']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW1']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EW1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW1_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EW1_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='poreale_EW4_3']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A1']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A1_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A1_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A1_4']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A10']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A10']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A10_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A10_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A10_3']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_EW1']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW1_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW1_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A7']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A7']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A7_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A7_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A3']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A3']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A3_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A3_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW6']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW6']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW6_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW6_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A1']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A1_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A1_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW4']/@owner"><xsl:attribute name='owner'>Faction.clan_zulizwe_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EW4']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW4_1']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EW4_2']/@culture"><xsl:attribute name='culture'>Culture.zulizwe</xsl:attribute></xsl:template>
</xsl:stylesheet>

