<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
    <xsl:output omit-xml-declaration="yes"/>
    <xsl:template match="@*|node()">
        <xsl:copy>
            <xsl:apply-templates select="@*|node()"/>
        </xsl:copy>
    </xsl:template>
    <!-- Iustrium -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_ES2']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES1_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES2_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES2_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES2_4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES8']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES8']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES8_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES8_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES8_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A4']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A4_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A4_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A4_4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES1']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_ES1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES1_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES1_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_ES1_4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A2']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A2_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A2_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A2_4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A13']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_A13']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A13_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A13_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_A13_3']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_ES4']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES4']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES4_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES4_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES5']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES5']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES5_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES5_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A8']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A8']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A8_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A8_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES1']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_ES1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES1_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_ES1_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A6']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A6']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A6_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A6_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A12']/@owner"><xsl:attribute name='owner'>Faction.clan_iustrium_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_A12']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A12_1']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_A12_2']/@culture"><xsl:attribute name='culture'>Culture.iustrium</xsl:attribute></xsl:template>

    <!-- Rekgeist -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_S1']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S1_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S1_3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S7']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S7']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S7_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S7_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S3']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_S3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S3_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_S3_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN1']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN1_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN1_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN1_3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN2']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_EN2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN2_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_EN2_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_S1']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S1_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S1_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S2']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S2_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S2_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S4']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S4']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S4_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S4_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S5']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_S5']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S5_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_S5_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN9']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN9']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN9_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN9_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN3']/@owner"><xsl:attribute name='owner'>Faction.clan_rekgeist_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_EN3']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN3_1']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_EN3_2']/@culture"><xsl:attribute name='culture'>Culture.rekgeist</xsl:attribute></xsl:template>

    <!-- Lysellois -->
    <!-- Cities -->
    <xsl:template match="Settlement[@id='town_V6']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V6']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_4']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V3']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V3_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V3_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V3_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V3_4']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V7']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V7']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V7_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V7_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V7_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V5']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V5']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V5_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V5_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V5_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V1']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V1_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V1_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V11']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_6</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='town_V11']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_5']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V6_6']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='village_V11_3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <!-- Castles -->
    <xsl:template match="Settlement[@id='castle_V3']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_1</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V3']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V3_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V3_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V6']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_2</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V6']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V6_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V6_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V1']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_3</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V1_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V1_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V2']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_4</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V2_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V2_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B1']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_5</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_B1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B1_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_B1_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V7']/@owner"><xsl:attribute name='owner'>Faction.clan_lysellois_7</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_V7']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V7_1']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
    <xsl:template match="Settlement[@id='castle_village_V7_2']/@culture"><xsl:attribute name='culture'>Culture.lysellois</xsl:attribute></xsl:template>
</xsl:stylesheet>

